// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoau1k4HCFCRqG293-eFDjtA2db5P_3Cw',
    appId: '1:654984880372:web:02276098015e8035a1fea1',
    messagingSenderId: '654984880372',
    projectId: 'smart-sallah-users',
    authDomain: 'smart-sallah-users.firebaseapp.com',
    storageBucket: 'smart-sallah-users.appspot.com',
    measurementId: 'G-CFVTG7VF6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGrS5cFbghXDzxPYHB_-u5jm5At40oT5k',
    appId: '1:654984880372:android:8e6ea5940f031e27a1fea1',
    messagingSenderId: '654984880372',
    projectId: 'smart-sallah-users',
    storageBucket: 'smart-sallah-users.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdcXdmQZWqYtU9ditbfYcBmqrZWyKmMIU',
    appId: '1:654984880372:ios:b3741fac1c1cae70a1fea1',
    messagingSenderId: '654984880372',
    projectId: 'smart-sallah-users',
    storageBucket: 'smart-sallah-users.appspot.com',
    iosClientId: '654984880372-ikib9vt492chifif0pv2cioujc2395kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sallaUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdcXdmQZWqYtU9ditbfYcBmqrZWyKmMIU',
    appId: '1:654984880372:ios:067d3a80e5082261a1fea1',
    messagingSenderId: '654984880372',
    projectId: 'smart-sallah-users',
    storageBucket: 'smart-sallah-users.appspot.com',
    iosClientId: '654984880372-jk8k8thvbt0ncgp64a752lchnj1uacht.apps.googleusercontent.com',
    iosBundleId: 'com.example.sallaUsers.RunnerTests',
  );
}
